/**
 * GENERATED by scripts/imaging-import.mjs — do not edit by hand.
 *
 * Real, openly licensed, de-identified images — X-ray, ultrasound, MRI, echo
 * and CT beyond the eight head CTs — exported as PNG frames under
 * /public/imaging. The patient named on screen is always the sample-kit
 * patient the study belongs to (src/data/imaging-ext.ts); the source below is
 * provenance and credit, never an identity.
 */

export interface ImageSeries {
  key: string
  /** stack: slices to scroll · single: one image · loop: frames to play. */
  kind: 'stack' | 'single' | 'loop'
  modality: 'X-ray' | 'Ultrasound' | 'MRI' | 'CT' | 'Echo'
  bodyPart: string
  /** The projection or sequence, as the frame's corner text says it: "PA", "DWI", "Parasternal long axis". */
  view: string
  frames: number
  rows: number
  columns: number
  /** Images the source held before subsampling. */
  seriesTotal: number
  /** How the pixels were windowed at export: "W1500L-600", or "auto" (percentile / the file's own). */
  window: string
  source: { dataset: string; licence: string; url: string; credit: string }
}

export const IMAGE_SERIES: Record<string, ImageSeries> = {
  'xr-0301': {"key":"xr-0301","kind":"single","modality":"X-ray","bodyPart":"Chest","view":"AP","frames":1,"rows":2164,"columns":2441,"seriesTotal":1,"window":"auto","source":{"dataset":"TCIA COVID-19-AR","licence":"CC BY 4.0","url":"https://www.cancerimagingarchive.net/collection/covid-19-ar/","credit":"TCIA COVID-19-AR, de-identified"}},
  'xr-0201': {"key":"xr-0201","kind":"single","modality":"X-ray","bodyPart":"Chest","view":"AP (upright)","frames":1,"rows":2330,"columns":2665,"seriesTotal":1,"window":"auto","source":{"dataset":"TCIA COVID-19-AR","licence":"CC BY 4.0","url":"https://www.cancerimagingarchive.net/collection/covid-19-ar/","credit":"TCIA COVID-19-AR, de-identified"}},
  'xr-0701': {"key":"xr-0701","kind":"single","modality":"X-ray","bodyPart":"Chest","view":"AP (portable, semi-upright)","frames":1,"rows":2330,"columns":2679,"seriesTotal":1,"window":"auto","source":{"dataset":"TCIA COVID-19-AR","licence":"CC BY 4.0","url":"https://www.cancerimagingarchive.net/collection/covid-19-ar/","credit":"TCIA COVID-19-AR, de-identified"}},
  'us-0101': {"key":"us-0101","kind":"single","modality":"Ultrasound","bodyPart":"Thyroid","view":"Right lobe, longitudinal","frames":1,"rows":412,"columns":598,"seriesTotal":1,"window":"auto","source":{"dataset":"Wikimedia Commons","licence":"CC BY-SA 3.0","url":"https://commons.wikimedia.org/wiki/File:Hashimoto-Thyreoiditis.JPG","credit":"Drahreg01, Wikimedia Commons"}},
  'xr-0601': {"key":"xr-0601","kind":"single","modality":"X-ray","bodyPart":"Chest","view":"AP (paediatric)","frames":1,"rows":1568,"columns":1874,"seriesTotal":1,"window":"auto","source":{"dataset":"Kermany et al., paediatric chest X-ray","licence":"CC BY 4.0","url":"https://data.mendeley.com/datasets/rscbjbr9sj/3","credit":"Kermany, Zhang, Goldbaum (Mendeley Data), de-identified"}},
  'us-0701': {"key":"us-0701","kind":"single","modality":"Ultrasound","bodyPart":"Right kidney","view":"Sagittal","frames":1,"rows":681,"columns":1007,"seriesTotal":1,"window":"auto","source":{"dataset":"Wikimedia Commons","licence":"CC BY 4.0","url":"https://commons.wikimedia.org/wiki/File:Normal_adult_kidney.jpg","credit":"K. L. Hansen, M. B. Nielsen, C. Ewertsen, Wikimedia Commons"}},
  'us-0901': {"key":"us-0901","kind":"single","modality":"Ultrasound","bodyPart":"Left kidney","view":"Sagittal","frames":1,"rows":2630,"columns":4197,"seriesTotal":1,"window":"auto","source":{"dataset":"Wikimedia Commons","licence":"CC BY-SA 4.0","url":"https://commons.wikimedia.org/wiki/File:Ultrasound_of_left_kidney_renal_parenchymal_disease.jpg","credit":"Cerevisae, Wikimedia Commons"}},
  'us-0401': {"key":"us-0401","kind":"single","modality":"Ultrasound","bodyPart":"Fetal head","view":"Transthalamic plane","frames":1,"rows":540,"columns":800,"seriesTotal":1,"window":"auto","source":{"dataset":"HC18","licence":"CC BY 4.0","url":"https://zenodo.org/records/1327317","credit":"HC18 challenge set (van den Heuvel et al.), de-identified"}},
  'us-0402': {"key":"us-0402","kind":"single","modality":"Ultrasound","bodyPart":"Fetal head","view":"Transthalamic plane","frames":1,"rows":540,"columns":800,"seriesTotal":1,"window":"auto","source":{"dataset":"HC18","licence":"CC BY 4.0","url":"https://zenodo.org/records/1327317","credit":"HC18 challenge set (van den Heuvel et al.), de-identified"}},
  'ec-1701': {"key":"ec-1701","kind":"loop","modality":"Echo","bodyPart":"Heart","view":"Apical two-chamber · rest, peak, recovery","frames":24,"rows":576,"columns":720,"seriesTotal":854,"window":"auto","source":{"dataset":"Wikimedia Commons","licence":"CC BY 2.0","url":"https://commons.wikimedia.org/wiki/File:Exercise_echocardiography_in_diabetic_patients_-_1476-7120-7-24-S4.wmv.ogv","credit":"Oliveira J et al., Cardiovasc Ultrasound 2009;7:24, Wikimedia Commons"}},
  'xr-1801': {"key":"xr-1801","kind":"single","modality":"X-ray","bodyPart":"Chest","view":"AP","frames":1,"rows":2330,"columns":2846,"seriesTotal":1,"window":"auto","source":{"dataset":"TCIA COVID-19-AR","licence":"CC BY 4.0","url":"https://www.cancerimagingarchive.net/collection/covid-19-ar/","credit":"TCIA COVID-19-AR, de-identified"}},
  'mr-2001': {"key":"mr-2001","kind":"stack","modality":"MRI","bodyPart":"Brain","view":"T1 axial","frames":28,"rows":256,"columns":256,"seriesTotal":37,"window":"auto","source":{"dataset":"Wikimedia Commons","licence":"CC BY-SA 3.0","url":"https://commons.wikimedia.org/wiki/File:Brain_MRI_T1_movie.gif","credit":"Dr. Laurent Hermoye (Imagilys), Wikimedia Commons"}},
  'us-2101': {"key":"us-2101","kind":"single","modality":"Ultrasound","bodyPart":"Liver","view":"Right upper quadrant, liver and right kidney","frames":1,"rows":892,"columns":1053,"seriesTotal":1,"window":"auto","source":{"dataset":"Wikimedia Commons","licence":"CC BY-SA 3.0","url":"https://commons.wikimedia.org/wiki/File:Steatosis_hepatis_-_Sonographie_001.jpg","credit":"Hellerhoff, Wikimedia Commons"}},
  'xr-2201': {"key":"xr-2201","kind":"single","modality":"X-ray","bodyPart":"Left knee","view":"AP, standing","frames":1,"rows":2652,"columns":2133,"seriesTotal":1,"window":"auto","source":{"dataset":"Wikimedia Commons","licence":"CC BY-SA 4.0","url":"https://commons.wikimedia.org/wiki/File:Osteoarthritis_on_X-ray.jpg","credit":"James Heilman, MD, Wikimedia Commons"}},
  'us-2401': {"key":"us-2401","kind":"single","modality":"Ultrasound","bodyPart":"Fetal head","view":"Transthalamic plane","frames":1,"rows":540,"columns":800,"seriesTotal":1,"window":"auto","source":{"dataset":"HC18","licence":"CC BY 4.0","url":"https://zenodo.org/records/1327317","credit":"HC18 challenge set (van den Heuvel et al.), de-identified"}},
  'us-2501': {"key":"us-2501","kind":"single","modality":"Ultrasound","bodyPart":"Right kidney","view":"Sagittal","frames":1,"rows":597,"columns":778,"seriesTotal":1,"window":"auto","source":{"dataset":"Wikimedia Commons","licence":"CC BY 4.0","url":"https://commons.wikimedia.org/wiki/File:Ultrasonography_of_hydronephrosis_due_to_ureteropelvic_junction_obstruction.jpg","credit":"K. L. Hansen, M. B. Nielsen, C. Ewertsen, Wikimedia Commons"}},
  'xr-2601': {"key":"xr-2601","kind":"single","modality":"X-ray","bodyPart":"Left breast","view":"CC, with magnified detail","frames":1,"rows":979,"columns":1382,"seriesTotal":1,"window":"auto","source":{"dataset":"Wikimedia Commons","licence":"CC BY-SA 4.0","url":"https://commons.wikimedia.org/wiki/File:Oelzysten_in_der_Mammographie_68W_-_MG_cc_-_001.jpg","credit":"Hellerhoff, Wikimedia Commons"}},
  'us-2701': {"key":"us-2701","kind":"single","modality":"Ultrasound","bodyPart":"Gallbladder","view":"Longitudinal","frames":1,"rows":576,"columns":784,"seriesTotal":1,"window":"auto","source":{"dataset":"Wikimedia Commons","licence":"CC BY-SA 3.0","url":"https://commons.wikimedia.org/wiki/File:Ultrasound_image_of_gallbladder_stone_Gallstone_091937515.jpg","credit":"Nevit Dilmen, Wikimedia Commons"}},
  'xr-2801': {"key":"xr-2801","kind":"single","modality":"X-ray","bodyPart":"Chest","view":"AP (portable)","frames":1,"rows":2330,"columns":2604,"seriesTotal":1,"window":"auto","source":{"dataset":"TCIA COVID-19-AR","licence":"CC BY 4.0","url":"https://www.cancerimagingarchive.net/collection/covid-19-ar/","credit":"TCIA COVID-19-AR, de-identified"}},
  'xr-2901': {"key":"xr-2901","kind":"single","modality":"X-ray","bodyPart":"Chest","view":"AP (trauma bay)","frames":1,"rows":2330,"columns":2846,"seriesTotal":1,"window":"auto","source":{"dataset":"TCIA COVID-19-AR","licence":"CC BY 4.0","url":"https://www.cancerimagingarchive.net/collection/covid-19-ar/","credit":"TCIA COVID-19-AR, de-identified"}},
  'ct-2901': {"key":"ct-2901","kind":"stack","modality":"CT","bodyPart":"Abdomen","view":"Axial, portal venous","frames":28,"rows":512,"columns":512,"seriesTotal":60,"window":"W400L40","source":{"dataset":"TCIA Pancreas-CT","licence":"CC BY 3.0","url":"https://www.cancerimagingarchive.net/collection/pancreas-ct/","credit":"TCIA Pancreas-CT (NIH Clinical Center), de-identified"}},
  'mr-3001': {"key":"mr-3001","kind":"single","modality":"MRI","bodyPart":"Brain","view":"DWI and ADC, axial","frames":1,"rows":420,"columns":723,"seriesTotal":1,"window":"auto","source":{"dataset":"Wikimedia Commons","licence":"CC BY 4.0","url":"https://commons.wikimedia.org/wiki/File:DWE_MRI_of_cerebral_infarction.png","credit":"Shazia Mirza and Sankalp Gokhale, Wikimedia Commons"}},
  'xr-3101': {"key":"xr-3101","kind":"single","modality":"X-ray","bodyPart":"Chest","view":"PA","frames":1,"rows":1097,"columns":1222,"seriesTotal":1,"window":"auto","source":{"dataset":"Wikimedia Commons","licence":"CC0","url":"https://commons.wikimedia.org/wiki/File:Chest_radiograph_of_a_lung_with_Kerley_B_lines.jpg","credit":"Mikael Häggström, Wikimedia Commons"}},
  'us-3201': {"key":"us-3201","kind":"single","modality":"Ultrasound","bodyPart":"Right iliac fossa","view":"Appendix, long and short axis","frames":1,"rows":627,"columns":1536,"seriesTotal":1,"window":"auto","source":{"dataset":"Wikimedia Commons","licence":"CC BY-SA 4.0","url":"https://commons.wikimedia.org/wiki/File:Phlegmonoese_Appendizitis_40W_-_US_-_001.jpg","credit":"Hellerhoff, Wikimedia Commons"}},
  'xr-3301': {"key":"xr-3301","kind":"single","modality":"X-ray","bodyPart":"Chest","view":"AP (portable)","frames":1,"rows":2330,"columns":2846,"seriesTotal":1,"window":"auto","source":{"dataset":"TCIA COVID-19-AR","licence":"CC BY 4.0","url":"https://www.cancerimagingarchive.net/collection/covid-19-ar/","credit":"TCIA COVID-19-AR, de-identified"}},
  'xr-3401': {"key":"xr-3401","kind":"single","modality":"X-ray","bodyPart":"Pelvis and left hip","view":"AP","frames":1,"rows":1117,"columns":1397,"seriesTotal":1,"window":"auto","source":{"dataset":"Wikimedia Commons","licence":"CC BY-SA 4.0","url":"https://commons.wikimedia.org/wiki/File:Mediale_Schenkelhalsfraktur_links_83W_-_CR_ap_-_001.jpg","credit":"Hellerhoff, Wikimedia Commons"}},
  'xr-3501': {"key":"xr-3501","kind":"single","modality":"X-ray","bodyPart":"Chest","view":"AP","frames":1,"rows":2322,"columns":2846,"seriesTotal":1,"window":"auto","source":{"dataset":"TCIA COVID-19-AR","licence":"CC BY 4.0","url":"https://www.cancerimagingarchive.net/collection/covid-19-ar/","credit":"TCIA COVID-19-AR, de-identified"}},
  'us-3501': {"key":"us-3501","kind":"single","modality":"Ultrasound","bodyPart":"Right kidney","view":"Sagittal","frames":1,"rows":2538,"columns":3521,"seriesTotal":1,"window":"auto","source":{"dataset":"Wikimedia Commons","licence":"CC BY-SA 4.0","url":"https://commons.wikimedia.org/wiki/File:Ultrasound_of_right_kidney_moderate_hydronephrosis.jpg","credit":"Cerevisae, Wikimedia Commons"}},
}

/** A frame's URL — under the deploy base, so a hosted copy finds its images. */
export function framePath(key: string, n: number): string {
  return `${import.meta.env.BASE_URL}imaging/${key}/frame-${String(n).padStart(2, '0')}.png`
}
